"""create sprays table

Revision ID: 73aaec4191cd
Revises: f15b12c955d1
Create Date: 2025-12-19 17:12:07.149316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73aaec4191cd"
down_revision: Union[str, Sequence[str], None] = "f15b12c955d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sprays",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("display_icon", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_sprays_uuid"), "sprays", ["uuid"], unique=False)
    op.create_table(
        "spray_levels",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("display_icon", sa.String(), nullable=True),
        sa.Column("spray_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spray_id"],
            ["sprays.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_spray_levels_uuid"), "spray_levels", ["uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spray_levels_uuid"), table_name="spray_levels")
    op.drop_table("spray_levels")
    op.drop_index(op.f("ix_sprays_uuid"), table_name="sprays")
    op.drop_table("sprays")
    # ### end Alembic commands ###
