"""create buddies table

Revision ID: 7c84cb766b90
Revises: a3595018fce8
Create Date: 2025-12-16 22:11:37.159264

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "7c84cb766b90"
down_revision: Union[str, Sequence[str], None] = "a3595018fce8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
