"""add skin levels and chromas

Revision ID: a1d0b1a45ccd
Revises: 9b1c329273bd
Create Date: 2025-12-16 21:01:44.581784

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "a1d0b1a45ccd"
down_revision: Union[str, Sequence[str], None] = "9b1c329273bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
