"""create sprays table

Revision ID: f15b12c955d1
Revises: c2e6cce43cc1
Create Date: 2025-12-19 17:07:00.662827

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "f15b12c955d1"
down_revision: Union[str, Sequence[str], None] = "c2e6cce43cc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
