"""add skin levels and chromas

Revision ID: 9b1c329273bd
Revises: 4c6fc40a32e6
Create Date: 2025-12-16 20:38:14.500268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b1c329273bd"
down_revision: Union[str, Sequence[str], None] = "4c6fc40a32e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chromas",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("display_icon", sa.String(), nullable=True),
        sa.Column("skin_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skin_id"],
            ["skins.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_chromas_uuid"), "chromas", ["uuid"], unique=False)
    op.create_table(
        "skin_levels",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("display_icon", sa.String(), nullable=True),
        sa.Column("skin_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skin_id"],
            ["skins.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_skin_levels_uuid"), "skin_levels", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skin_levels_uuid"), table_name="skin_levels")
    op.drop_table("skin_levels")
    op.drop_index(op.f("ix_chromas_uuid"), table_name="chromas")
    op.drop_table("chromas")
    # ### end Alembic commands ###
