"""create buddies table

Revision ID: a3595018fce8
Revises: fca86a9c1fdf
Create Date: 2025-12-16 22:05:35.901390

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "a3595018fce8"
down_revision: Union[str, Sequence[str], None] = "fca86a9c1fdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
