"""create buddies table

Revision ID: c2e6cce43cc1
Revises: 7c84cb766b90
Create Date: 2025-12-16 22:14:33.878234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2e6cce43cc1"
down_revision: Union[str, Sequence[str], None] = "7c84cb766b90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buddies",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("display_icon", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_buddies_uuid"), "buddies", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_buddies_uuid"), table_name="buddies")
    op.drop_table("buddies")
    # ### end Alembic commands ###
