"""buddies added

Revision ID: fca86a9c1fdf
Revises: a1d0b1a45ccd
Create Date: 2025-12-16 21:58:30.870961

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "fca86a9c1fdf"
down_revision: Union[str, Sequence[str], None] = "a1d0b1a45ccd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
